### ISSUE TITLE
🎨 Sanitise `.github` folder

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#144]
Set an implement standards for GitHub Actions workflows - Example:

- Don't quote YAML string unless required
- Permissions scoped to job
- Names must be sensible and define what is going on
- Use step IDs
- Use version SHAs
- File name follows patten of `${type}-${action}.yaml` - types:
  - `documentation-*.yml` - tech-docs
  - `repository-*.yml` - formatters, repo and security
  - `service-*.yml` - data platform services
  - `terraform-*.yml` - data platform Terraform

```yaml
name: Do a thing

on:
  issues:
    types:
      - opened

permissions: read-all

jobs:
  do-a-thing:
    name: Do a thing
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Do a thing
        id: do_thing
        uses: actions/action@actionversionsha # action version release
        with:
          input: ${{ var.EXAMPLE_VARIABLE }}
          input2: ${{ secrets.EXAMPLE_SECRET }}
```

- [x] Update CODEOWNERS
- [x] Update labeler
