### ISSUE TITLE
⬆️  Upgrade JupyterLab to support Python >3.10

### ISSUE THREAD

**Issue by jhpyke** [ministryofjustice/analytical-platform#2348]
### Describe the feature request.

This ticket would cover the work required to release a new version of `jupyter-lab` to users running on `Python 3.10`

**Recommended Approach**:

- [x] Update the [dockerfile](https://github.com/ministryofjustice/analytics-platform-jupyter-notebook) to reflect the new base version of python
- [ ] ~Update the [helmchart](https://github.com/ministryofjustice/analytics-platform-helm-charts) accordingly~
- [x] Create a new release on control panel

**Acceptance Criteria**

- [ ] A version of `jupyter-lab` running on `python 3.10` is available to AP users

### Describe the context.

The current AP allows for the launching of several variants of `jupyter-lab`, however all of the currently available images are based on Python 3.9. However, a change to the base version of python used by Airflow has lead to [the current guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/airflow/instructions/dag-pipeline/#validate-from-the-command-line-optiona) becoming invalid, as the validation process requires a base python version of `3.10`.

### Value / Purpose

This would allow our user guidance to be applicable once more, providing a high quality of service to users. Beyond the immediate value to airflow users, keeping up-to-date versions of python available to users allows users to write code targeting newer features of base python, giving them the advantages of the continued development of the language.

### User Types

Any python users of AP.

### Definition of Done
- [ ] Complete Recommended Approach above
- [ ] Update [the current guidance](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/airflow/instructions/dag-pipeline/#validate-from-the-command-line-optiona)

**Comment by michaeljcollinsuk** [comment]
We also need to update the python version used in the rstudio images, see message in [#ask-data-platform channel](https://mojdt.slack.com/archives/C04VBJTKY58/p1702031809409569)

**Comment by jacobwoffenden** [comment]
Stats on Jupyter image usage as of 29/01/24

```yaml
allspark-notebook:
  - v2.0.0: 4
  - v3.0.0: 36
  - v3.0.1: 41
  - v3.1.13: 131

datascience-notebook:
  - lab-3.1.12: 43
  - v3.1.13: 64
  - v3.1.14: 119

datascience-notebook-moj: # no idea where this is from
  - lab-3.1.12: 59

oracle-datascience-notebook: {}
```
