### ISSUE TITLE
🔱 SPIKE: HTTP01 resolver on DPAT EKS

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#2364]
### Describe the feature request.

I would like to use cert-manager's HTTP01 resolver to validate certificate requests

### Value / Purpose

Allowing HTTP01 would mean not having to migrate Route 53 zones to the account where cert-manager is running OR allowing cross-account Route 53 access

### User Types

Platform Engineering

**Comment by jacobwoffenden** [comment]
I have:

- Delegated `assets.development.data-platform.service.justice.gov.uk` from `data-platform-development` to `data-platform-apps-and-tools-development` https://github.com/ministryofjustice/modernisation-platform-environments/pull/4004
- Created a new `ClusterIssuer` on DPAT development EKS
- Created a new `Namespace`, `Deployment`, `Service` and `Ingress` on DPAT development EKS

### `ClusterIssuer`

```yaml
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-http01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "data-platform-tech+certificates@digital.justice.gov.uk"
    privateKeySecretRef:
      name: letsencrypt-production-http01
    solvers:
      - http01:
          ingress:
            ingressClassName: default
```

### `Namespace`, `Deployment`, `Service` and `Ingress`

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: static-assets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-assets
  namespace: static-assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-assets
  template:
    metadata:
      labels:
        app: static-assets
    spec:
      containers:
        - name: static-assets
          image: ghcr.io/ministryofjustice/data-platform-static-assets@sha256:0b55c9eaecbd0fb517a4d32bedee9e682335eb74cadefba0a31cb874b3e1750d
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: static-assets
  namespace: static-assets
spec:
  selector:
    app: static-assets
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-assets
  namespace: static-assets
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-http01
    external-dns.alpha.kubernetes.io/hostname: assets.development.data-platform.service.justice.gov.uk
spec:
  ingressClassName: default
  tls:
    - hosts:
        - assets.development.data-platform.service.justice.gov.uk
      secretName: static-assets-tls
  rules:
    - host: assets.development.data-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: static-assets
                port:
                  number: 8080
```

With this running, <https://assets.development.data-platform.service.justice.gov.uk> is now accessible
