### ISSUE TITLE
 ✨ Create new OIDC role for GitHub runner

### ISSUE THREAD

**Issue by rolakeo-mojo** [ministryofjustice/analytical-platform#3942]
### Describe the feature request.

I'm a Data Scientist within the CJS Dashboard App team and I want to connect to the Analytical Platform via GitHub Runners so I can run a test which requires access to a specific bucket.

Technical notes:

This is the [repo](https://github.com/moj-analytical-services/airflow-cjs-dashboard-data) in which the GitHub runners run on and will need access to the `alpha-cjs-scorecard` bucket.
We need an OICD role which can be assumed by a GitHub runner, that has sufficient permissions to access (read, write and delete from) the data in the above bucket.

### Value / Purpose

So that we can run an Integration Test - improve the quality/level of testing.

**Comment by rolakeo-mojo** [comment]
For reference, another member of our team asked for a similar request last year (https://github.com/ministryofjustice/data-platform/issues/2951). Please if someone is able to pick this up soon, I have a ticket that is currently blocked while waiting for this request. Thank you! :)

**Comment by AntFMoJ** [comment]
@RolakeO-mojo can I just confirm if you need the runner to have permission to write and delete objects in the `alpha-cjs-scorecard` bucket in addition to read permissions?

Just to note, the previous ticket you referenced above only required read permission.

**Comment by rolakeo-mojo** [comment]
Yes, this runner needs to be able to write out a dummy dataset then delete it at the end of the test so it needs write and delete permissions also please.

**Comment by AntFMoJ** [comment]
@RolakeO-mojo a role with the required permissions has been created, the ARN is `arn:aws:iam::593291632749:role/github-airflow-cjs-dashboard-data`. Please let us know how you get on with using the role and if it is working as expected. Thank you

**Comment by rolakeo-mojo** [comment]
Thank you for getting this role sorted, I tried using it but I'm getting this error in the github actions:

`Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentity`

I've attached a photo of my yaml code and also copied part of it below if someone can help on this please?

```
name: run-tests
run-name: Run tests
on: [pull_request]
permissions:
  id-token: write
  contents: read
jobs:
  tests-job:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::593291632749:role/github-airflow-cjs-dashboard-data
    - name: Check out repo
      uses: actions/checkout@v3
```
![Screenshot 2024-04-18 at 15 05 23](https://github.com/ministryofjustice/data-platform/assets/131277838/5ccc7c0d-2b77-4465-9561-80f24a01da55)
