### ISSUE TITLE
🤖 Make Dependabot configuration generator run as a PR action

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#459]
Instead of running on merge to main or schedule, we should have it run as part of the pull request process (if *.tf or *Dockerfile* have changed in the tree)

Something like:

```yaml
---
name: Generate Dependabot configuration

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - **/*.tf
      - **/*Dockerfile*
```
