### ISSUE TITLE
🐞 Airflow workflow unable to execute AWS CLI

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#6248]
### Describe the bug.

```
[2024-12-06, 10:38:18 UTC] {{pod_manager.py:228}} INFO - [Errno 13] Permission denied: '/.aws'
[2024-12-06, 10:38:18 UTC] {{pod_manager.py:228}} INFO - [Errno 13] Permission denied: '/.aws'
```

### To Reproduce

Run [p1-offloc-dev.extract-upload](https://github.com/moj-analytical-services/airflow/blob/main/environments/dev/dags/p1-offloc-dev/extract-upload.py) on APC

### Expected Behaviour

AWS CLI works

### Additional context

Workflow: https://23f37892-d1d1-4d9f-a03d-b8a53581fd20.c0.eu-west-1.airflow.amazonaws.com/log?dag_id=p1-offloc-dev.extract-upload&task_id=extract&execution_date=2024-12-06T10%3A38%3A01.471825%2B00%3A00&map_index=-1

DAG: https://github.com/moj-analytical-services/airflow/blob/main/environments/dev/dags/p1-offloc-dev/extract-upload.py

Role: https://github.com/moj-analytical-services/airflow/blob/main/environments/dev/roles/airflow_dev_p1_offloc.yaml

Image: https://github.com/moj-analytical-services/p1-offloc-export/actions/runs/6972920402

MOJAP Airflow Tools: https://github.com/moj-analytical-services/mojap-airflow-tools/blob/master/mojap_airflow_tools/operators.py

**Comment by jacobwoffenden** [comment]
I've run the image via

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-debug
  namespace: airflow
spec:
  containers:
    - name: aws-cli-debug
      image: 189157455002.dkr.ecr.eu-west-1.amazonaws.com/p1-offloc-export:v4.0.0-dev
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"

```

_Note the lack of a security context, `basic_kubernetes_pod_operator` does not expose or set these._

Output:

```bash
root@aws-cli-debug:/files# which aws
/usr/local/bin/aws
root@aws-cli-debug:/files# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
