### ISSUE TITLE
⚙️ Allow multi-task jobs to specify global environment variables

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#6872]
### Describe the task.

Multi-task jobs use this logic for setting environment variables:

```jinja
{%- if task.env_vars %}
  env_vars:
  {%- for k, v in task.env_vars.items() %}
    {{ k }}: {{ v }}
  {%- endfor %}
{%- endif %}
```

If a user wanted to set `FOO: "bar"` for every task they would have to do it for each task, for example

```yaml
dag:
  tasks:
    first:
      env_vars:
        FOO: "bar"
    second:
      env_vars:
        FOO: "bar"
```

We should let them specify global variables, where the task overrides the global

```yaml
dag:
  env_vars:
    FOO: "bar"
  tasks:
    first:
      env_vars:
        FOO: "baz"
    second:
      env_vars:
        FOO: "qux"
```

### Steps to Address

Update either `scripts/workflow_generator/main.py` or `scripts/workflow_generator/templates/workflow.yml.j2` to achieve this
