### ISSUE TITLE
🐞 IAM policy is too large when all options are enabled

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#6873]
### Describe the bug.

```
│ Error: updating IAM Policy (arn:aws:iam::593291632749:policy/airflow-development-analytical-platform-example): operation error IAM: CreatePolicyVersion, https response error StatusCode: 409, RequestID: b7b8270e-7563-41eb-9106-750e75ec0b74, LimitExceeded: Cannot exceed quota for PolicySize: 6144
│ 
│   with module.airflow["analytical-platform/example"].module.iam_policy[0].aws_iam_policy.policy[0],
│   on .terraform/modules/airflow.iam_policy/modules/iam-policy/main.tf line 1, in resource "aws_iam_policy" "policy":
│    1: resource "aws_iam_policy" "policy" {
```

### To Reproduce

1. Turn on all IAM options

For example

```yaml
iam:
  athena: write
  bedrock: true
  glue: true
  kms:
    - arn:aws:kms:eu-west-2:123456789012:key/mrk-12345678909876543212345678909876
  s3_deny:
    - mojap-compute-development-dummy/deny1/*
    - mojap-compute-development-dummy/deny2/*
  s3_read_only:
    - mojap-compute-development-dummy/readonly1/*
    - mojap-compute-development-dummy/readonly2/*
  s3_read_write:
    - mojap-compute-development-dummy/readwrite1/*
    - mojap-compute-development-dummy/readwrite2/*
  s3_write_only:
    - mojap-compute-development-dummy/writeonly1/*
    - mojap-compute-development-dummy/writeonly2/*
```

### Expected Behaviour

IAM policy and role is generated

### Additional context

statements like Athena, Bedrock and Glue (excluding `GluePassRole` statement) are static, so maybe we can break them out into standalone policies and attach them to the role if enabled
