### ISSUE TITLE
🐞 Airflow environment variables cannot handle integers

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#6929]
### Describe the bug.

When passing an environment variable that is a number, it breaks

### To Reproduce

1. Create a workflow with

```yaml
...
  tasks:
    task_one:
      env_vars:
        FOO: "bar"
        TASK: "1"
```

it gets passed to DAG factory as 

```yaml
  tasks:
    task_one:
      operator: analytical_platform.standard_operator.AnalyticalPlatformStandardOperator
      name: analytical-platform-example-multi-task-task_one
      task_id: analytical-platform-example-multi-task-task_one
      compute_profile: general-spot-1vcpu-4gb
      image: 509399598587.dkr.ecr.eu-west-2.amazonaws.com/moj-analytical-services/analytical-platform-airflow-python-example:2.0.0
      env_vars:
        FOO: bar
        TASK: 1
```

which then explodes with

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod in version \"v1\" cannot be handled as a Pod: json: cannot unmarshal number into Go struct field EnvVar.spec.containers.env.value of type string","reason":"BadRequest","code":400}
```

See https://airflow.compute.development.analytical-platform.service.justice.gov.uk/dags/analytical-platform.example-multi-task/grid?dag_run_id=manual__2025-02-18T11%3A46%3A11.363983%2B00%3A00&task_id=task_one&tab=logs

### Expected Behaviour

environment variables are passed as strings to Kubernetes
