### ISSUE TITLE
💅 Update all GitHub Actions workflows to use version hashes

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/analytical-platform#79]
Currently we have a lot of steps that don't pin version SHAs. Updating as per the below allows Dependabot to raise a PR when a version change is detected upstream

```yaml
jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: example/action:v1
```

to

```yaml
jobs:
  do-a-thing:
    runs-on: ubuntu-latest
    steps:
      - uses: example/action:123456789 # v1.0.0
```
